### ISSUE TITLE
Ultraplex only recognizes the last 3' barcode   

### ISSUE THREAD

**Issue by arivers** [ulelab/ultraplex#47]
I have a set of 12 forward by 9 reverse in-line barcode pairs, which I pass in as pairs in a CSV barcode file. 

For example:

```
AATAGAGCAA,AACCATAGAA
AATAGAGCAA,ACGCCTTGTT
AATAGAGCAA,ATGGTTGACT
AATAGAGCAA,GATAGGCCGA
...
```
When I run this command
 
```
ultraplex -i testdata/GT01_S1_L001_R1_001.fastq.gz -i2 testdata/GT01_S1_L001_R2_001.fastq.gz -b data/f2-6.csv --dont_build_reference
```

Ultraplex identifies all forward barcodes but it only identifies the last barcode in a lexographically sorted list of the unique reverse barcodes.  If I delete all primer pairs from my barcode file with that last barcode and rerun then it finds just the second to last barcode.  I also verified the reverse barcodes are present with grep.

I've attached sample data you can use to reproduce the error:

[f2-6.csv](https://github.com/ulelab/ultraplex/files/12919713/f2-6.csv)
[GT01_S1_L001_R1_001.fastq.gz](https://github.com/ulelab/ultraplex/files/12919721/GT01_S1_L001_R1_001.fastq.gz)
[GT01_S1_L001_R2_001.fastq.gz](https://github.com/ulelab/ultraplex/files/12919722/GT01_S1_L001_R2_001.fastq.gz)

**Comment by arivers** [comment]
Okay thanks.  For others who may have misread, it is the first 5' barcode followed by all possible reverse complemented 3' barcodes:

```
AATAGAGCAA,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
CGCACATGGC,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
CTAACTGTAA,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
CTGTGTTAGG,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
CTTATGGAAT,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
GCTTACGGAC,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
GGCCTGTCCT,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
GGCGAGATGG,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
TAAGGAACGT,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
TCAATCCATT,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
TCCGACCTCG,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
TCGTATGCGG,AACCATAGAA,ACGCCTTGTT,ATGGTTGACT,GATAGGCCGA,GGTTGCGAGG,TAAGCATCCA,TAAGCATCCA,TATTGCGCTC,TTCTACATAC
```
Here's a Python snippet to convert two files with forward and reverse barcodes to create a combinatorial demultiplexing:

```{python}
revdict = []
with open("barcodes_rev_rc.txt") as rhandle:
    for line in rhandle:
       revdict.append(line.strip())


with open("barcodes_fwd.txt") as fhandle:
    for line in fhandle:
       flist = [line.strip()]
       flist.extend(revdict)
       print(",".join(flist))
```

I also found that this can be done with Cutadapt https://cutadapt.readthedocs.io/en/stable/guide.html#combinatorial-demultiplexing but Ultraplex makes prettier file names.

**Comment by Delayed-Gitification** [comment]
Thanks for taking the time to write that up!
