### ISSUE TITLE
Ultraplex taking 1TB of RAM and did not yet even start writing out a single nucleotide???

### ISSUE THREAD

**Issue by mmokrejs** [ulelab/ultraplex#51]
Hi,
  there must be some terrible misunderstanding on my side. You claim in https://pubmed.ncbi.nlm.nih.gov/34286104/ this tool is ultra fast and efficient, and so on ... I wanted just to demultiplex FASTQ reads from R1 and R2 files based on a barcode at the very beginning of each of those reads. I assume the two streams can be consumed and immediately written into as many files as dynamically determined to be needed.

  By reading the cmdline docs I realize I have to explicitly disable QUAL trimming and do not know how to disable adapter searches. Also, it turns out only mismatches are allowed in the barcodes, no InDels, that is suboptimal. I can run e.g. `agrep --max-errors=2 '^ATGCATGC'` on my own then.

  Why is some `reference` being built at all if one asks for demultiplexing by a barcode, present and the very beginning of a read? Please improve the documentation.

```
$ ultraplex -i ../foo_R1.fastq.gz -i2 ../foo_R2.fastq.gz -d . -t 32 -m5 1 -m3 1 -q 0 -b ../barcodes_only.tsv

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@   @@@@   .@@   @@@@@@@          @@         @@@@@@    (@@@@@        @@@    @@@@@@@         @@    @@@    @
@@@@   @@@@    @@   ,@@@@@@@@@    @@@@@    @@@   @@@@   (   @@@@   @@@   @@    @@@@@@@   @@@@@@@@@@   #   @@@@
@@@   &@@@    @@    @@@@@@@@@%   @@@@@         @@@@(   @    @@@         @@    @@@@@@@         @@@@@     @@@@@@
@@    @@@    @@    @@@@@@@@@@   @@@@@    @@    @@@          @@   .@@@@@@@*   @@@@@@@    @@@@@@@@.   @    @@@@@
@@@       @@@@.        @@@@@   @@@@@&   @@@.   &   &@@@@    @    @@@@@@@@         @          @    @@@@    @@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Namespace(inputfastq='../foo_R1.fastq.gz', barcodes='../barcodes_only.tsv', directory='.', fiveprimemismatches=1, threeprimemismatches=1, three_prime_only=False, tso_seq='', phredquality=0, threads=32, adapter='AGATCGGAAGAGCACACGTCTGAA', outputprefix='demux', sbatchcompression=False, ultra=False, ignore_space_warning=False, final_min_length=20, phredquality_5_prime=0, input_2='../foo_R2.fastq.gz', adapter2='AGATCGGAAGAGCGTCGTG', min_trim=3, ignore_no_match=False, dont_build_reference=False, keep_barcode=False)
Warning - large barcodes detected!
It may be faster to use option '--dont_build_reference'!
```

BTW, it would be much easier if ultraplex supported multiple columns in a input CSV file, like:

```
#sample_name\tbarcode1_in_fwd_read\tbarcode2_in_rev_read
```

Why inventing a complicated samplename assignment spanning two explanatory pages in `README.md`?

I had to discard the samplenames in my first column:

```
$ awk -F '\t' '{print $2,$3}' ../barcodes.tsv
GCCCCTCT TTCTCAGA
TAGTCATC GGGATTAT
CCGTGGGT GTTAGTCA
TAAGTAGA CATAACCT
GCAACGTG AGGTGCAA
AACTTTAC CCGTACAC
ACTAGGCG GTCTCGTG
ATTTGCAC CGGTCTTT
AATGCATG TCTGAAAC
CTTTTTAT CTAAGGGG
ACGCAATC GCACCTAG
TATCCACT CAGCACGT
AATCAGGG GGGTACGG
GCTGCCTT GAAGAGCG
AGTTAGTA CAGAGCCA
GACAGCCC TGCCGTGG
AGCACGGT TGCGTCTC
ATGTTGTC ATGGGTGG
CTCCCCGC TGTCCACG
TATGGCAG AAAACGCC
AGATGAGT CTCACAAT
ATCGTACA ACGACTAC
TTCTATCC CTAGACTG
CAGGTCGC TCTATGCG
CGGAATTG TGTGTTGA
$
```

Ultraplex cannot name the output files `"${samplename}"."${barcode1}"+"${barcode2}"_R[12].fastq.gz` automagically? 

At 1.7TB of RAM usage and 52minutes runtime at a single thread and with NO demultiplexed FASTQ output written so far I think this tools does not do what thought.

I hope this will help other newcomers in the future. Thank you.

```
^CTraceback (most recent call last):
  File "/blah/anaconda3/envs/ultraplex/bin/ultraplex", line 11, in <module>
    sys.exit(main())
  File "/blah/anaconda3/envs/ultraplex/lib/python3.9/site-packages/ultraplex/__main__.py", line 1950, in main
    workers, all_conn_r, all_conn_w = start_workers(
  File "/blah/anaconda3/envs/ultraplex/lib/python3.9/site-packages/ultraplex/__main__.py", line 1245, in start_workers
    worker = WorkerProcess(
  File "/blah/anaconda3/envs/ultraplex/lib/python3.9/site-packages/ultraplex/__main__.py", line 473, in __init__
    self._five_p_bc_dict = make_5p_bc_dict(
  File "/blah/anaconda3/envs/ultraplex/lib/python3.9/site-packages/ultraplex/__main__.py", line 72, in make_5p_bc_dict
    seqs = make_all_seqs(seq_length)
  File "/blah/anaconda3/envs/ultraplex/lib/python3.9/site-packages/ultraplex/__main__.py", line 243, in make_all_seqs
    new_seqs.append(seq + nt)
KeyboardInterrupt
```

Both the `seq + nt` and `.append()` are on their own performance killers, btw.

**Comment by Delayed-Gitification** [comment]
I think given that the problems described above (exploding RAM usage, failure to write out expected combinations) are almost certainly due to the barcodes.csv (not TSV!) being incorrectly formatted, I will close this issue.

**Comment by mmokrejs** [comment]
I have only 1-to-1 barcode pairs, each of the members is unique, all should be visible in verbatin in the sequence at the very start as demonstrated by the `grep`. Still somehow it did not work out. I am doing something wrong.

```
$ cat ../barcodes_only.csv
GCCCCTCT,TTCTCAGA
TAGTCATC,GGGATTAT
CCGTGGGT,GTTAGTCA
TAAGTAGA,AGGTTATG
GCAACGTG,AGGTGCAA
AACTTTAC,CCGTACAC
ACTAGGCG,GTCTCGTG
ATTTGCAC,CGGTCTTT
AATGCATG,TCTGAAAC
CTTTTTAT,CTAAGGGG
ACGCAATC,GCACCTAG
TATCCACT,CAGCACGT
AATCAGGG,GGGTACGG
GCTGCCTT,GAAGAGCG
AGTTAGTA,CAGAGCCA
GACAGCCC,TGCCGTGG
AGCACGGT,TGCGTCTC
ATGTTGTC,ATGGGTGG
CTCCCCGC,TGTCCACG
TATGGCAG,AAAACGCC
AGATGAGT,CTCACAAT
ATCGTACA,ACGACTAC
TTCTATCC,CTAGACTG
CAGGTCGC,TCTATGCG
CGGAATTG,TGTGTTGA
$
```

32 threads was just a blind hope it will help with speed but if every thread/process grabbed same amount of buffers, etc., indeed this was a bad choice. But I saw only one process using `top` AFAICT and eating all that memory, `RSS`.

I never cutadapt for that but will have a look. Actually I am now hoping `ATM` in UMI-tools. faster will probably be to open both `R1` and `R2` files with gzopen, parse with biopython into obnject and test for record.seq.startswith(barcode_fwd1) or  
record.seq.startswith(barcode_rev1) to be `True`. I just thought there will be a tool for this and overcoming not only mismatches but also InDels. Otherwise even with a `grep` I can get a list of matching reads, unify them and extract those reads into dedicated FASTQ files. `agrep` would be slightly better but sadly unlike `grep` does not print lines before and after the matching line (`grep -B 1 -A 2` is helpful to get complete matching FASTQ entry). Even worse, it recognizes the cmdline switches but they are for a different purpose. Pity.

**Comment by mmokrejs** [comment]
No, they are in VERBATIM as they should appear in the FASTA/Q sequence, quite likely this is the cause. As I showed, `grep` finds them as they are in front of each sequence line. No reason to revert-complement them. So I will just reverse-complement those after the comma and be done with this. Thanks for the hint.
